project_id = "izkfudforlcfcnyygzyh"

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.send-sale-notification]
verify_jwt = false

[functions.send-donation-thanks]
verify_jwt = false
